import { useEffect,useRef,useState } from 'react'
import { Link,useNavigate } from 'react-router'
import { CheckCircle2,UploadCloud,Play,BrainCircuit,Trash2 } from 'lucide-react'
import { api } from '../api/http'
import { clearCharacterLabLocal,clearTrainingLocal,exportModelArchive,hasModel,importModelArchive,importZip,loadDataset,loadResult,predict,saveDataset,saveResult,toBase64,train,type CharacterDataset,type CharacterResult } from '../character-store'
import { useProjectStore } from '../store/project'
import { ApiMessage,Page,workflow } from './AppShell'

type LabState={project_id:string;dataset:null|{file_name:string;content_type:string;labels:string[];samples:number;updated_at:string};training:null|{file_name:string;content_type:string;labels:string[];epochs:number;accuracy:number;loss:number;history:CharacterResult['history'];updated_at:string}}
const MAX_ARCHIVE=15*1024*1024
function useProject(){return useProjectStore(s=>s.id)}
function Card({children}:{children:React.ReactNode}){return <section className="panel character-card">{children}</section>}
async function syncLab(projectId:string){
  const remote=await api.request<LabState>(`/projects/${encodeURIComponent(projectId)}/character-lab`)
  let data=await loadDataset(projectId)
  if(remote.dataset&&data?.updatedAt!==remote.dataset.updated_at){const archive=await api.blob(`/projects/${encodeURIComponent(projectId)}/character-lab/dataset-file`);data=await importZip(projectId,archive,()=>undefined,remote.dataset.updated_at)}
  if(!remote.dataset&&data){await clearCharacterLabLocal(projectId);data=undefined}
  let result=await loadResult(projectId)
  if(remote.training&&(!result||result.updatedAt!==remote.training.updated_at||!await hasModel(projectId))){const archive=await api.blob(`/projects/${encodeURIComponent(projectId)}/character-lab/model-file`);await importModelArchive(projectId,archive);result={projectId,labels:remote.training.labels,epochs:remote.training.epochs,accuracy:remote.training.accuracy,loss:remote.training.loss,history:remote.training.history,updatedAt:remote.training.updated_at};await saveResult(result)}
  if(!remote.training&&result){await clearTrainingLocal(projectId);result=undefined}
  return {data,result}
}
export function DatasetPage(){
  const id=useProject(),nav=useNavigate(),input=useRef<HTMLInputElement>(null),[data,setData]=useState<CharacterDataset>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('')
  useEffect(()=>{if(id)void syncLab(id).then(({data:next})=>setData(next)).catch(e=>setError((e as Error).message))},[id])
  async function load(file?:File){if(!id||!file)return;if(file.size>MAX_ARCHIVE){setError('El ZIP puede pesar como mÃ¡ximo 15 MB.');return}if(data&&!window.confirm('Reemplazar el dataset borrarÃ¡ el modelo y los resultados anteriores. Â¿Continuar?'))return;setBusy(true);setError('');setProgress('');try{const next=await importZip(id,file,(done,total)=>setProgress(`Procesando ${done} de ${total} imÃ¡genes...`));setProgress('Guardando copia segura en el proyecto...');const saved=await api.request<LabState>(`/projects/${encodeURIComponent(id)}/character-lab/dataset`,{method:'PUT',body:{file_name:file.name,content_type:file.type==='application/x-zip-compressed'?'application/x-zip-compressed':'application/zip',archive_base64:await toBase64(file),labels:next.labels,samples:next.samples.length}});const dated={...next,updatedAt:saved.dataset!.updated_at};await saveDataset(dated);await clearTrainingLocal(id);setData(dated);setProgress('Dataset guardado y sincronizado.') }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function clear(){if(!id||!window.confirm('Se borrarÃ¡n el ZIP, el modelo y todos los resultados de entrenamiento de este proyecto. El proyecto seguirÃ¡ existiendo.'))return;setBusy(true);setError('');try{await api.request(`/projects/${encodeURIComponent(id)}/character-lab`,{method:'DELETE'});await clearCharacterLabLocal(id);setData(undefined);setProgress('Proyecto limpio. Puedes cargar otro ZIP.') }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 1 · RECONOCIMIENTO DE CARACTERES</span><h1>Carga tu dataset etiquetado</h1><p>Usa un ZIP con una carpeta por carácter. Cada imagen debe contener un solo número, letra o símbolo.</p></div></div><Card><input ref={input} hidden type="file" accept=".zip,application/zip" onChange={e=>void load(e.target.files?.[0])}/><UploadCloud size={42}/><h2>Dataset ZIP de caracteres</h2><p><code>0/001.png</code>, <code>0/002.png</code>, <code>A/001.png</code>… Máximo 15 MB.</p><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Procesando...':data?'Reemplazar ZIP':'Seleccionar ZIP'}</button><p role="status">{progress}</p></Card><ApiMessage error={error}/>{data&&<Card><div className="status"><CheckCircle2 size={18}/>Dataset guardado en el proyecto</div><h2>{data.samples.length} imágenes · {data.labels.length} etiquetas</h2><p>Etiquetas: {data.labels.join(', ')}. Se recuperará al abrir este proyecto desde otra PC.</p><div className="actions end"><button className="secondary" disabled={busy} onClick={()=>void clear()}><Trash2 size={16}/>Limpiar datos y entrenamiento</button><button className="primary" onClick={()=>nav(workflow('/preparacion',id))}>Preparar dataset</button></div></Card>}</Page>
}
export function PreparationPage(){const id=useProject(),nav=useNavigate(),[data,setData]=useState<CharacterDataset>(),[error,setError]=useState('');useEffect(()=>{if(id)void syncLab(id).then(x=>setData(x.data)).catch(e=>setError((e as Error).message))},[id]);return <Page stepper><ApiMessage error={error}/>{!data?<Card><h1>Aún no hay dataset</h1><Link to={workflow('/dataset',id)}>Cargar ZIP</Link></Card>:<><div className="page-title"><div><span className="eyebrow">PASO 2 · PREPARACIÓN REAL</span><h1>Imágenes listas para la CNN</h1><p>Las imágenes se redimensionan a 28 × 28 píxeles, se convierten a escala de grises y se separan por etiqueta.</p></div></div><Card><ul className="character-list"><li>Entrada: PNG/JPG con un carácter por imagen.</li><li>Normalización: píxeles entre 0 y 1; se invierte automáticamente un fondo claro.</li><li>División: 80% entrenamiento y 20% prueba por cada etiqueta.</li><li>Clases detectadas: {data.labels.join(', ')}.</li></ul><div className="actions end"><button className="primary" onClick={()=>nav(workflow('/modelo',id))}>Ver modelo CNN</button></div></Card></>}</Page>}
export function ModelPage(){const id=useProject(),nav=useNavigate(),[data,setData]=useState<CharacterDataset>(),[error,setError]=useState('');useEffect(()=>{if(id)void syncLab(id).then(x=>setData(x.data)).catch(e=>setError((e as Error).message))},[id]);return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 3 · ÚNICO MODELO DISPONIBLE</span><h1>CNN para caracteres individuales</h1><p>Este proyecto solo admite clasificación de caracteres; no hay modelos genéricos ni simulación.</p></div></div><ApiMessage error={error}/><Card><BrainCircuit size={42}/><h2>Red neuronal convolucional pequeña</h2><p>28×28×1 → Conv2D(8) → MaxPool → Conv2D(16) → Dense(32) → {data?.labels.length??'?'} etiquetas.</p><p>Las etiquetas se obtienen de tu ZIP y la red se crea al entrenar.</p><div className="actions end"><button className="primary" disabled={!data} onClick={()=>nav(workflow('/entrenamiento',id))}>Entrenar modelo</button></div></Card></Page>}
export function TrainingPage(){
  const id=useProject(),nav=useNavigate(),[data,setData]=useState<CharacterDataset>(),[result,setResult]=useState<CharacterResult>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[epoch,setEpoch]=useState(0)
  useEffect(()=>{if(id)void syncLab(id).then(x=>{setData(x.data);setResult(x.result)}).catch(e=>setError((e as Error).message))},[id])
  async function run(){if(!id)return;setBusy(true);setError('');setEpoch(0);try{const next=await train(id,12,info=>setEpoch(info.epoch));const archive=await exportModelArchive(id);const saved=await api.request<LabState>(`/projects/${encodeURIComponent(id)}/character-lab/training`,{method:'PUT',body:{file_name:'modelo-caracteres.zip',content_type:'application/zip',archive_base64:await toBase64(archive),labels:next.labels,epochs:next.epochs,accuracy:next.accuracy,loss:next.loss,history:next.history}});const dated={...next,updatedAt:saved.training!.updated_at};await saveResult(dated);setResult(dated)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 4 · ENTRENAMIENTO REAL EN EL NAVEGADOR</span><h1>Entrena tu CNN</h1><p>El cálculo ocurre localmente y el ZIP, modelo y resultados se guardan de forma privada en tu proyecto.</p></div></div><Card>{data?<><h2>{data.samples.length} ejemplos · {data.labels.length} clases</h2><button className="primary" disabled={busy} onClick={()=>void run()}><Play size={17}/>{busy?`Entrenando época ${epoch}/12...`:'Entrenar 12 épocas'}</button></>:<Link to={workflow('/dataset',id)}>Primero carga el ZIP</Link>}</Card><ApiMessage error={error}/>{result&&<Card><div className="status"><CheckCircle2 size={18}/>Entrenamiento guardado y sincronizado</div><h2>Accuracy de prueba: {(result.accuracy*100).toFixed(1)}%</h2><p>Loss: {result.loss.toFixed(4)} · {result.epochs} épocas</p><div className="actions end"><button className="primary" onClick={()=>nav(workflow('/evaluacion',id))}>Ver evaluación</button></div></Card>}</Page>
}
export function EvaluationPage(){const id=useProject(),nav=useNavigate(),[result,setResult]=useState<CharacterResult>(),[error,setError]=useState('');useEffect(()=>{if(id)void syncLab(id).then(x=>setResult(x.result)).catch(e=>setError((e as Error).message))},[id]);return <Page stepper><ApiMessage error={error}/>{!result?<Card><h1>Aún no hay entrenamiento</h1><Link to={workflow('/entrenamiento',id)}>Entrenar modelo</Link></Card>:<><div className="page-title"><div><span className="eyebrow">PASO 5 · EVALUACIÓN</span><h1>Resultados reales de tu dataset</h1><p>La accuracy se calculó con el 20% de ejemplos reservados por etiqueta.</p></div></div><Card><h2>{(result.accuracy*100).toFixed(1)}% accuracy</h2><p>Loss final: {result.loss.toFixed(4)}. Etiquetas: {result.labels.join(', ')}.</p><ol className="character-list">{result.history.map(h=><li key={h.epoch}>Época {h.epoch}: accuracy {(h.accuracy*100).toFixed(1)}% · loss {h.loss.toFixed(4)}</li>)}</ol><div className="actions end"><button className="primary" onClick={()=>nav(workflow('/prediccion',id))}>Probar una imagen</button></div></Card></>}</Page>}
export function PredictionPage(){const id=useProject(),input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File>(),[answer,setAnswer]=useState<{label:string;confidence:number;values:{label:string;confidence:number}[]} >(),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{if(id)void syncLab(id).catch(e=>setError((e as Error).message))},[id]);async function run(){if(!id||!file)return;setBusy(true);setError('');try{await syncLab(id);setAnswer(await predict(id,file))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 6 · PRUEBA</span><h1>Reconoce un carácter nuevo</h1><p>Selecciona una imagen PNG o JPG que no haya sido usada durante el entrenamiento.</p></div></div><Card><input ref={input} hidden type="file" accept="image/png,image/jpeg" onChange={e=>{setFile(e.target.files?.[0]);setAnswer(undefined)}}/><button className="secondary" onClick={()=>input.current?.click()}>{file?.name??'Seleccionar imagen'}</button><button className="primary" disabled={!file||busy} onClick={()=>void run()}>{busy?'Analizando...':'Predecir carácter'}</button></Card><ApiMessage error={error}/>{answer&&<Card><h2>Predicción: {answer.label}</h2><p>Confianza: {(answer.confidence*100).toFixed(1)}%</p><ul className="character-list">{answer.values.sort((a,b)=>b.confidence-a.confidence).map(v=><li key={v.label}>{v.label}: {(v.confidence*100).toFixed(1)}%</li>)}</ul></Card>}</Page>}
