import { useRef,useState } from 'react'
import { ArrowRight, BrainCircuit, Image as ImageIcon, Target } from 'lucide-react'
import { Link,useNavigate } from 'react-router'
import { api } from '../api/http'
import { type Classroom,type Project } from '../api/types'
import { useResource } from '../api/useResource'
import { useProjectStore } from '../store/project'
import { ApiMessage,Header,workflow } from './AppShell'

export default function CreateProjectDynamic(){const nav=useNavigate(),{name,setName,select}=useProjectStore(),rooms=useResource<Classroom[]>('/classrooms?limit=100'),[classroom,setClassroom]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),sending=useRef(false);async function create(){if(sending.current||!name.trim())return;sending.current=true;setBusy(true);setError('');try{const project=await api.request<Project>('/projects',{method:'POST',body:{title:name.trim(),project_type:'character_recognition',...(classroom?{classroom_id:classroom}:{})}});select(project);nav(workflow('/dataset',project.id))}catch(e){setError((e as Error).message)}finally{sending.current=false;setBusy(false)}}return <><Header/><main className="page wizard-page"><Link className="back-link" to="/">← Volver al inicio</Link><div className="wizard-dynamic-layout"><section className="panel form-panel wizard-main-panel"><span className="eyebrow">NUEVO PROYECTO</span><h1>Entrena un reconocedor de caracteres</h1><p className="wizard-intro">Este laboratorio permite entrenar una CNN real con tus imágenes etiquetadas de números, letras o símbolos individuales.</p><label>Nombre del proyecto<input required maxLength={180} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Reconocedor de números"/></label><label>Salón (opcional)<select value={classroom} onChange={e=>setClassroom(e.target.value)}><option value="">Proyecto personal</option>{rooms.data?.filter(r=>r.status==='active').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><ApiMessage {...rooms} retry={rooms.reload}/><section className="dynamic-config-card"><div className="dynamic-config-heading"><Target size={20}/><div><strong>Único tipo disponible</strong><p>Clasificación de un carácter por imagen.</p></div></div><div className="dynamic-config-grid"><div><small>Dataset</small><strong>ZIP con carpetas por etiqueta</strong></div><div><small>Modelo</small><strong>CNN pequeña con TensorFlow.js</strong></div><div><small>Evaluación</small><strong>Accuracy y loss reales</strong></div><div><small>Almacenamiento</small><strong>Local en este navegador</strong></div></div></section><ApiMessage error={error}/><div className="actions wizard-actions"><Link className="secondary button-link" to="/">Cancelar</Link><button className="primary" disabled={busy||!name.trim()} onClick={()=>void create()}>{busy?'Creando…':'Crear y cargar dataset'} <ArrowRight size={17}/></button></div></section><aside className="wizard-side"><section className="panel live-preview blue"><span className="eyebrow">FLUJO DEL LABORATORIO</span><ImageIcon size={42}/><h2>ZIP → CNN → Predicción</h2><p>Sube ejemplos etiquetados, entrena localmente y prueba una imagen nueva.</p></section><section className="friendly-note"><BrainCircuit size={20}/><div><strong>Entrenamiento real</strong><p>El modelo no es una simulación ni usa una API externa.</p></div></section></aside></div></main></>}
