import { useState, type ReactNode } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router'
import {
  Activity, ArrowRight, BarChart3, Bell, BrainCircuit, Camera, CheckCircle2, CircleHelp,
  Code2, Database, Download, FileText, FolderOpen, Gauge, HardDrive, Home, Image as ImageIcon,
  Link2, Network, Pause, Play, Plus, Save, Search, Settings2, Share2, SlidersHorizontal,
  Sparkles, Split, Square, Target, TrendingUp, Trophy, UploadCloud, WandSparkles,
} from 'lucide-react'
import { Background, Controls, MiniMap, ReactFlow, type Edge, type Node } from '@xyflow/react'
import { useProjectStore, type ProjectLevel } from './store/project'
import { Header, Page, workflow } from './components/AppShell'
import { Dashboard, ProjectsPage, ProjectDetail, ClassroomsPage, ClassroomDetail } from './components/ConnectedPages'
import { StudentsPage } from './components/StudentsPage'
import { TeachersPage } from './components/TeachersPage'

type IconType = typeof Home

const flowSteps = [
  ['/dataset', 'Datos'], ['/preparacion', 'Preparación'], ['/modelo', 'Modelo'], ['/editor', 'Pipeline'],
  ['/entrenamiento', 'Entrenar'], ['/evaluacion', 'Evaluar'], ['/prediccion', 'Probar'],
] as const

const palette: Array<[string, IconType]> = [
  ['Datos', Database], ['Procesar', SlidersHorizontal], ['Modelos', BrainCircuit],
  ['Entrenar', Settings2], ['Evaluar', BarChart3], ['Usar', Play],
]

function DatasetPage(){const navigate=useNavigate();return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 1</span><h1>Cargar dataset</h1><p>Selecciona el origen de tus datos y revisa su balance.</p></div><button className="secondary"><CircleHelp size={17}/>Ver guía</button></div><div className="source-tabs"><button className="active"><UploadCloud size={19}/>Subir archivos</button><button><Camera size={19}/>Webcam</button><button><Database size={19}/>Ejemplo</button><button><Link2 size={19}/>URL</button><button><HardDrive size={19}/>Drive</button></div><div className="two-column dataset-layout"><section className="panel upload-panel"><UploadCloud size={42}/><h3>Arrastra y suelta tus imágenes aquí</h3><p>JPG, PNG o WEBP · máximo 10 MB por archivo</p><button className="secondary">Seleccionar archivos</button><div className="thumb-row"><span>🐶</span><span>🐱</span><span>🐕</span><span>🐈</span><span>🐶</span><span>＋</span></div></section><aside className="panel dataset-summary"><div className="status"><CheckCircle2 size={18}/>Listo para usar</div><h3>Resumen del dataset</h3><div className="stats"><div><strong>1,010</strong><small>imágenes</small></div><div><strong>2</strong><small>clases</small></div></div><div className="class-bar"><div><span>Perro</span><b>520 · 51.5%</b></div><i style={{width:'51.5%'}}/></div><div className="class-bar purple"><div><span>Gato</span><b>490 · 48.5%</b></div><i style={{width:'48.5%'}}/></div></aside></div><div className="actions end"><button className="primary" onClick={()=>navigate('/preparacion')}>Usar este dataset <ArrowRight size={17}/></button></div></Page>}

function PreparationPage(){const navigate=useNavigate();const cards:Array<[IconType,string,string,string]>=[[ImageIcon,'Resize','224 × 224 px','Redimensiona todas las imágenes a un tamaño uniforme.'],[SlidersHorizontal,'Normalizar','Rango 0–1','Escala los píxeles para estabilizar el aprendizaje.'],[Split,'Dividir datos','70 / 15 / 15','Separa entrenamiento, validación y prueba.']];return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 2</span><h1>Preparar datos</h1><p>Configura las transformaciones antes de entrenar.</p></div></div><div className="pipeline-strip">{cards.map(([Icon,title],i)=><div key={title}><span><Icon size={19}/></span><strong>{title}</strong>{i<cards.length-1&&<ArrowRight size={18}/>}</div>)}</div><div className="three-grid">{cards.map(([Icon,title,detail,text])=><section className="panel config-card" key={title}><div className="config-title"><span className="card-icon violet"><Icon size={20}/></span><strong>{title}</strong><CheckCircle2 size={18}/></div><label>Configuración<input value={detail} readOnly/></label><p>{text}</p></section>)}</div><div className="tip"><WandSparkles size={20}/><div><strong>Aprende mientras creas</strong><p>La preparación consistente mejora el entrenamiento y permite evaluar el modelo con datos separados.</p></div></div><div className="actions end"><button className="secondary"><Save size={17}/>Guardar cambios</button><button className="primary" onClick={()=>navigate('/modelo')}>Continuar <ArrowRight size={17}/></button></div></Page>}

function ModelPage(){const navigate=useNavigate();const [selected,setSelected]=useState('CNN');const models=['Regresión logística','Árbol de decisión','Random Forest','Red neuronal','CNN','ResNet18','MobileNet','Transformer'];return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO 3</span><h1>Elige y configura tu modelo</h1><p>Explora alternativas y empieza por una opción comprensible.</p></div></div><div className="model-layout"><div className="model-grid">{models.map(model=><button key={model} onClick={()=>setSelected(model)} className={selected===model?'model-card selected':'model-card'}><BrainCircuit size={24}/><strong>{model}</strong><small>{model==='CNN'?'Ideal para imágenes · Intermedio':'Disponible para explorar'}</small>{selected===model&&<CheckCircle2 size={18}/>}</button>)}</div><aside className="panel inspector"><span className="eyebrow">MODELO SELECCIONADO</span><h2>{selected}</h2><p>Configuración sugerida para el prototipo educativo.</p><label>Capas<input value="3" readOnly/></label><label>Filtros<input value="32, 64, 128" readOnly/></label><label>Activación<input value="ReLU" readOnly/></label><label>Dropout<input value="0.25" readOnly/></label><div className="network-preview"><span>Entrada</span><ArrowRight size={15}/><span>Capa 1</span><ArrowRight size={15}/><span>Capa 2</span><ArrowRight size={15}/><span>Salida</span></div><button className="primary full" onClick={()=>navigate(workflow('/editor',useProjectStore.getState().id))}>Usar modelo <ArrowRight size={17}/></button></aside></div></Page>}

const nodes:Node[]=[
  {id:'dataset',position:{x:30,y:110},data:{label:'📚 Dataset\n1,010 ejemplos'},style:{background:'#eef6ff',border:'1px solid #90c2ff',width:150}},
  {id:'resize',position:{x:230,y:55},data:{label:'🧹 Preparar\nTransformación'},style:{background:'#f5efff',border:'1px solid #c6a7ff',width:150}},
  {id:'normalize',position:{x:230,y:175},data:{label:'🎚️ Normalizar\n0–1'},style:{background:'#f5efff',border:'1px solid #c6a7ff',width:150}},
  {id:'split',position:{x:440,y:110},data:{label:'✂️ Dividir datos\n70 / 15 / 15'},style:{background:'#eef6ff',border:'1px solid #90c2ff',width:150}},
  {id:'cnn',position:{x:650,y:110},data:{label:'🧠 Modelo\nConfigurable'},style:{background:'#ecfbf5',border:'2px solid #42b88a',width:150}},
  {id:'train',position:{x:860,y:55},data:{label:'⚙️ Entrenar\n20 épocas'},style:{background:'#f3efff',border:'1px solid #aa91ff',width:150}},
  {id:'eval',position:{x:860,y:175},data:{label:'📊 Evaluar\nMétricas'},style:{background:'#fff7e7',border:'1px solid #f2c36b',width:150}},
]
const edges:Edge[]=[{id:'e1',source:'dataset',target:'resize'},{id:'e2',source:'resize',target:'normalize'},{id:'e3',source:'normalize',target:'split'},{id:'e4',source:'split',target:'cnn'},{id:'e5',source:'cnn',target:'train'},{id:'e6',source:'train',target:'eval'}]

function EditorPage(){const navigate=useNavigate();const{name,type,level}=useProjectStore();return <Page stepper><div className="editor-head"><div><span className="eyebrow">EDITOR VISUAL · {type} · {level}</span><h1>{name}</h1></div><div><Link className="secondary button-link" to="/proyectos"><FolderOpen size={17}/>Mis proyectos</Link><button className="secondary" disabled title="Los cambios del editor aún no se guardan"><Save size={17}/>Guardar</button><button className="primary" onClick={()=>navigate(workflow('/entrenamiento',useProjectStore.getState().id))}><Play size={17}/>Ejecutar proyecto</button></div></div><div className="editor-layout"><aside className="panel block-palette"><h3>Bloques</h3><div className="search small"><Search size={15}/><span>Buscar bloques...</span></div>{palette.map(([label,Icon])=><button key={label}><Icon size={18}/><span>{label}</span><Plus size={15}/></button>)}</aside><section className="flow-canvas"><ReactFlow nodes={nodes} edges={edges} fitView><Background gap={20} size={1}/><Controls/><MiniMap zoomable pannable/></ReactFlow></section><aside className="panel inspector editor-inspector"><span className="eyebrow">PROPIEDADES</span><h2>Modelo</h2><p>Configura el bloque seleccionado.</p><label>Arquitectura<input value="Modelo del proyecto" readOnly/></label><label>Iteraciones<input value="20" readOnly/></label><label>Optimizador<input value="Adam" readOnly/></label><label>Learning rate<input value="0.001" readOnly/></label><div className="tip compact"><CircleHelp size={17}/><div><strong>Aprende mientras construyes</strong><p>Cada bloque representa una etapa del pipeline de IA.</p></div></div></aside></div></Page>}

function TrainingPage(){const navigate=useNavigate();const metrics:Array<[string,string,IconType]>=[['Accuracy entrenamiento','92.4%',Target],['Accuracy validación','89.7%',Gauge],['Loss','0.238',Activity]];return <Page stepper><section className="training-hero"><div><span className="eyebrow">ENTRENAMIENTO SIMULADO</span><h1>Entrenando modelo</h1><p>Esta pantalla usa datos mock para validar la experiencia antes de conectar el servidor ML.</p><div className="progress"><i style={{width:'40%'}}/></div><div className="progress-meta"><span>Época 8 / 20</span><strong>40%</strong></div></div><BrainCircuit size={72}/></section><div className="metric-grid">{metrics.map(([label,value,Icon])=><div className="metric-card" key={label}><Icon size={22}/><span>{label}</span><strong>{value}</strong><small>Actualizado hace unos segundos</small></div>)}</div><div className="chart-grid"><section className="panel chart-card"><h3>Accuracy por época</h3><div className="fake-chart"><svg viewBox="0 0 500 180" preserveAspectRatio="none"><polyline points="0,155 60,135 120,112 180,95 240,72 300,62 360,45 420,34 500,26" fill="none" stroke="currentColor" strokeWidth="4"/><polyline className="purple-line" points="0,160 60,143 120,123 180,108 240,88 300,78 360,62 420,54 500,45" fill="none" strokeWidth="4"/></svg></div></section><section className="panel log-card"><h3>Registro</h3><code>✓ Dataset preparado</code><code>✓ Modelo inicializado</code><code>✓ Época 7 completada</code><code>→ Entrenando época 8/20...</code></section></div><div className="actions between"><div><button className="secondary"><Pause size={17}/>Pausar</button><button className="danger"><Square size={15}/>Detener</button></div><button className="primary" onClick={()=>navigate(workflow('/evaluacion',useProjectStore.getState().id))}>Ver resultado simulado <ArrowRight size={17}/></button></div></Page>}

function EvaluationPage(){const navigate=useNavigate();return <Page stepper><div className="success-banner"><CheckCircle2 size={32}/><div><span className="eyebrow">EVALUACIÓN COMPLETADA</span><h1>Tu modelo tiene un buen resultado</h1><p>Ahora revisa las métricas y dónde se equivoca.</p></div></div><div className="metric-grid four">{[['Accuracy','91.7%'],['Precision','90.2%'],['Recall','92.1%'],['F1 Score','91.1%']].map(([label,value])=><div className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>Resultado mock</small></div>)}</div><div className="two-column eval-layout"><section className="panel"><h3>Matriz de confusión</h3><div className="confusion"><span></span><b>Clase A</b><b>Clase B</b><b>Clase A</b><strong>92</strong><em>8</em><b>Clase B</b><em>6</em><strong>94</strong></div></section><section className="panel"><h3>Errores comunes</h3><div className="mistakes"><div>🔎 <span>Ejemplo mal clasificado</span></div><div>🔎 <span>Confianza baja</span></div><div>🔎 <span>Caso ambiguo</span></div></div><div className="tip compact"><Sparkles size={17}/><div><strong>Qué significa accuracy</strong><p>91.7% indica que el modelo acierta aproximadamente 92 de cada 100 ejemplos.</p></div></div></section></div><div className="actions end"><button className="secondary" onClick={()=>navigate(workflow('/editor',useProjectStore.getState().id))}>Mejorar modelo</button><button className="primary" onClick={()=>navigate(workflow('/prediccion',useProjectStore.getState().id))}>Probar modelo <ArrowRight size={17}/></button></div></Page>}

function PredictionPage(){return <Page stepper><div className="page-title"><div><span className="eyebrow">PASO FINAL</span><h1>Probar modelo</h1><p>Comprueba cómo se sentirá usar el modelo entrenado.</p></div></div><div className="two-column prediction-layout"><section className="panel test-card"><div className="tab-row"><button className="active"><UploadCloud size={17}/>Subir entrada</button><button><Camera size={17}/>Capturar</button></div><div className="prediction-drop">🧪<strong>ejemplo_de_prueba</strong><small>Entrada de demostración</small></div><button className="primary full"><Play size={17}/>Probar entrada</button><div className="prediction-result"><div><small>Predicción</small><h2>CLASE A</h2><span>Alta confianza</span></div><div className="probabilities"><p><span>Clase A</span><b>97%</b></p><i style={{width:'97%'}}/><p><span>Clase B</span><b>3%</b></p><i className="short"/></div></div></section><section className="panel code-card"><div className="tab-row"><button className="active"><Code2 size={17}/>Ver código</button><button><Share2 size={17}/>Exportar</button></div><pre><code>{`import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(2, activation="softmax")
])

model.compile(optimizer="adam", metrics=["accuracy"])`}</code></pre><div className="actions end"><button className="secondary"><Share2 size={17}/>Compartir</button><button className="primary"><Download size={17}/>Descargar modelo</button></div></section></div></Page>}

function NotFound(){return <Page><div className="empty-state"><h1>404</h1><p>Esta pantalla todavía no existe.</p><Link className="button-link primary" to="/">Volver al inicio</Link></div></Page>}

export default function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/proyectos" element={<ProjectsPage/>}/><Route path="/proyectos/:id" element={<ProjectDetail/>}/><Route path="/salones" element={<ClassroomsPage/>}/><Route path="/salones/:id" element={<ClassroomDetail/>}/><Route path="/alumnos" element={<StudentsPage/>}/><Route path="/docentes" element={<TeachersPage/>}/><Route path="/dataset" element={<DatasetPage/>}/><Route path="/preparacion" element={<PreparationPage/>}/><Route path="/modelo" element={<ModelPage/>}/><Route path="/editor" element={<EditorPage/>}/><Route path="/entrenamiento" element={<TrainingPage/>}/><Route path="/evaluacion" element={<EvaluationPage/>}/><Route path="/prediccion" element={<PredictionPage/>}/><Route path="*" element={<NotFound/>}/></Routes>}
