import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router'
import { AuthProvider } from './auth/AuthProvider'
import { Gate } from './Experience'
import '@xyflow/react/dist/style.css'
import './styles.css'
import './projects.css'
import './carbon-friendly.css'
import './dynamic-project.css'
import './responsive.css'
import './connected.css'
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><AuthProvider><Gate/></AuthProvider></BrowserRouter></StrictMode>)
